version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.x
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 385020026243.dkr.ecr.ap-southeast-2.amazonaws.com
      - REPOSITORY_URI=385020026243.dkr.ecr.ap-southeast-2.amazonaws.com/nest-ecs
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo printing docker images
      - docker images
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - DOCKER_CONTAINER_NAME=nest-ecr
      - echo Writing image definitions file...
      - printf '[{"name":"nest-ecs testing","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > ${CODEBUILD_SRC_DIR}/imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json