version: "3"
services:
  nest-ec2:
    build: .
    image: 385020026243.dkr.ecr.ap-southeast-2.amazonaws.com/nest-ecs:latest
    environment:
      - MONGO_USER=mongo
      - MONGO_PASSWORD=password
      - MONGO_IP=mongo
      - MONGO_PORT=27017
    ports:
      - "3000:3000"